import type { Course, Discipline } from "./types";

// Curated from https://www.odm-engineer.com/ — Thai engineering tutoring catalog.
// Faithful to the site's discipline split (Mechanical/Civil/Electrical/Industrial)
// plus design + theory tracks the user requested.
const raw: Omit<Course, "id" | "slug" | "enrolled" | "rating" | "embedding">[] = [
  {
    title: "Engineering Mechanics: Statics",
    titleTh: "กลศาสตร์วิศวกรรม: สถิตยศาสตร์",
    discipline: "mechanical",
    level: "intro",
    hours: 24,
    price: 2400,
    summary:
      "วิเคราะห์แรง โมเมนต์ สมดุล ระบบเฟรม-ทรัส และจุดศูนย์ถ่วง — ปูพื้นวิศวะทุกสาย",
    topics: ["force", "moment", "equilibrium", "truss", "frame", "centroid", "friction"],
    thumbnail: "/img/courses/statics.svg",
  },
  {
    title: "Dynamics & Vibrations",
    titleTh: "พลศาสตร์และการสั่นสะเทือน",
    discipline: "mechanical",
    level: "intermediate",
    hours: 28,
    price: 2800,
    summary: "การเคลื่อนที่ของอนุภาคและวัตถุแข็ง พลังงาน โมเมนตัม การสั่นแบบฮาร์โมนิก",
    topics: ["kinematics", "kinetics", "energy", "momentum", "harmonic", "vibration"],
    thumbnail: "/img/courses/dynamics.svg",
  },
  {
    title: "Mechanics of Materials",
    titleTh: "กลศาสตร์ของวัสดุ",
    discipline: "mechanical",
    level: "intermediate",
    hours: 30,
    price: 2900,
    summary: "ความเค้น-ความเครียด การโก่งตัวของคาน การบิด และทฤษฎี failure",
    topics: ["stress", "strain", "beam", "torsion", "buckling", "mohr"],
    thumbnail: "/img/courses/mom.svg",
  },
  {
    title: "Thermodynamics",
    titleTh: "อุณหพลศาสตร์",
    discipline: "mechanical",
    level: "intermediate",
    hours: 26,
    price: 2700,
    summary: "กฎข้อที่ 1-2 วัฏจักร Carnot/Rankine/Otto/Diesel เอนโทรปี",
    topics: ["first-law", "second-law", "entropy", "carnot", "rankine", "otto"],
    thumbnail: "/img/courses/thermo.svg",
  },
  {
    title: "Fluid Mechanics",
    titleTh: "กลศาสตร์ของไหล",
    discipline: "mechanical",
    level: "intermediate",
    hours: 26,
    price: 2700,
    summary: "ของไหลสถิต Bernoulli โมเมนตัม Navier-Stokes เบื้องต้น flow ในท่อ",
    topics: ["hydrostatic", "bernoulli", "momentum", "viscous", "pipe-flow"],
    thumbnail: "/img/courses/fluid.svg",
  },
  {
    title: "Heat Transfer",
    titleTh: "การถ่ายเทความร้อน",
    discipline: "mechanical",
    level: "advanced",
    hours: 22,
    price: 2500,
    summary: "การนำ การพา การแผ่รังสี และการออกแบบ heat exchanger",
    topics: ["conduction", "convection", "radiation", "heat-exchanger"],
    thumbnail: "/img/courses/heat.svg",
  },
  {
    title: "Structural Analysis",
    titleTh: "การวิเคราะห์โครงสร้าง",
    discipline: "civil",
    level: "intermediate",
    hours: 28,
    price: 2800,
    summary: "วิเคราะห์โครงสร้าง determinate/indeterminate, slope-deflection, moment distribution",
    topics: ["truss", "beam", "frame", "indeterminate", "slope-deflection"],
    thumbnail: "/img/courses/struct.svg",
  },
  {
    title: "Reinforced Concrete Design",
    titleTh: "ออกแบบคอนกรีตเสริมเหล็ก",
    discipline: "civil",
    level: "advanced",
    hours: 24,
    price: 2700,
    summary: "ออกแบบคาน เสา ฐานราก ตามมาตรฐาน ACI/มยผ.",
    topics: ["beam-design", "column", "footing", "shear", "aci"],
    thumbnail: "/img/courses/rc.svg",
  },
  {
    title: "Soil Mechanics",
    titleTh: "ปฐพีกลศาสตร์",
    discipline: "civil",
    level: "intermediate",
    hours: 22,
    price: 2400,
    summary: "การจำแนกดิน การไหลซึม การยุบตัว แรงเฉือน และเสถียรภาพลาดดิน",
    topics: ["classification", "seepage", "consolidation", "shear-strength", "slope"],
    thumbnail: "/img/courses/soil.svg",
  },
  {
    title: "Circuit Analysis",
    titleTh: "การวิเคราะห์วงจรไฟฟ้า",
    discipline: "electrical",
    level: "intro",
    hours: 24,
    price: 2400,
    summary: "KVL/KCL Thevenin Norton AC/DC ทรานเซียนต์ และ phasor",
    topics: ["kvl", "kcl", "thevenin", "norton", "phasor", "transient"],
    thumbnail: "/img/courses/circuit.svg",
  },
  {
    title: "Electromagnetic Fields",
    titleTh: "สนามแม่เหล็กไฟฟ้า",
    discipline: "electrical",
    level: "advanced",
    hours: 26,
    price: 2700,
    summary: "Maxwell equations, transmission lines, waveguides, antennas",
    topics: ["maxwell", "wave", "transmission-line", "antenna"],
    thumbnail: "/img/courses/em.svg",
  },
  {
    title: "Signals & Systems",
    titleTh: "สัญญาณและระบบ",
    discipline: "electrical",
    level: "intermediate",
    hours: 24,
    price: 2600,
    summary: "Fourier, Laplace, z-transform, LTI systems, sampling",
    topics: ["fourier", "laplace", "z-transform", "lti", "sampling"],
    thumbnail: "/img/courses/signals.svg",
  },
  {
    title: "Operations Research",
    titleTh: "การวิจัยดำเนินงาน",
    discipline: "industrial",
    level: "intermediate",
    hours: 22,
    price: 2400,
    summary: "Linear programming, simplex, transportation, queueing, simulation",
    topics: ["lp", "simplex", "transportation", "queueing", "simulation"],
    thumbnail: "/img/courses/or.svg",
  },
  {
    title: "Production & Quality Control",
    titleTh: "การผลิตและควบคุมคุณภาพ",
    discipline: "industrial",
    level: "intermediate",
    hours: 20,
    price: 2200,
    summary: "Forecasting, MRP, inventory, six-sigma, control charts",
    topics: ["forecast", "mrp", "inventory", "six-sigma", "spc"],
    thumbnail: "/img/courses/qc.svg",
  },
  {
    title: "Engineering Drawing & CAD",
    titleTh: "เขียนแบบวิศวกรรมและ CAD",
    discipline: "design",
    level: "intro",
    hours: 18,
    price: 1900,
    summary: "Orthographic, isometric, GD&T, AutoCAD, SolidWorks essentials",
    topics: ["orthographic", "isometric", "gdt", "autocad", "solidworks"],
    thumbnail: "/img/courses/cad.svg",
  },
  {
    title: "Product Design Methodology",
    titleTh: "ระเบียบวิธีออกแบบผลิตภัณฑ์",
    discipline: "design",
    level: "intermediate",
    hours: 16,
    price: 1900,
    summary: "Design thinking, requirement, concept generation, FMEA, prototyping",
    topics: ["design-thinking", "requirement", "concept", "fmea", "prototype"],
    thumbnail: "/img/courses/design.svg",
  },
  {
    title: "Engineering Mathematics",
    titleTh: "คณิตศาสตร์วิศวกรรม",
    discipline: "theory",
    level: "intermediate",
    hours: 30,
    price: 2900,
    summary: "ODE, PDE, linear algebra, complex analysis, numerical methods",
    topics: ["ode", "pde", "linear-algebra", "complex", "numerical"],
    thumbnail: "/img/courses/math.svg",
  },
  {
    title: "Control Systems",
    titleTh: "ระบบควบคุม",
    discipline: "theory",
    level: "advanced",
    hours: 24,
    price: 2700,
    summary: "Transfer function, root locus, Bode, PID, state-space",
    topics: ["transfer-function", "root-locus", "bode", "pid", "state-space"],
    thumbnail: "/img/courses/control.svg",
  },
];

const discPrefix: Record<Discipline, string> = {
  mechanical: "ME",
  civil: "CE",
  electrical: "EE",
  industrial: "IE",
  design: "DE",
  theory: "TH",
};

export const seedCourses: Course[] = raw.map((c, i) => ({
  ...c,
  id: `${discPrefix[c.discipline]}-${(i + 101).toString()}`,
  slug: c.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
  enrolled: Math.floor(40 + Math.random() * 360),
  rating: Math.round((4.2 + Math.random() * 0.7) * 10) / 10,
}));
